// ============================================================
// lang.js - Multi-Language Support System
// Default: English | Supported: 10+ languages
// ============================================================

const LANGUAGES = {
    en: {
        name: "English", flag: "🇬🇧",
        // Auth
        welcomeBack: "Welcome",
        dashboardSubtitle: "Welcome back, {owner}! Here's how {shop} is performing today.",
        loginSubtitle: "Login to your showroom",
        emailPassword: "📧 Email / Password",
        phoneOTP: "📱 Phone Number",
        emailId: "Email ID",
        password: "Password",
        loginBtn: "Login",
        sendOTP: "Send OTP 📱",
        noAccount: "Don't have account?",
        signUpLink: "Sign Up",
        createAccount: "Create New Account",
        signupSubtitle: "Register your showroom",
        yourName: "Your Name",
        howRegister: "How to register?",
        emailPwd: "Email + Password",
        phoneotp: "Phone OTP",
        confirmPassword: "Confirm Password",
        createAccountBtn: "Create Account ✨",
        alreadyAccount: "Already have account?",
        loginLink: "Login",
        otpEnter: "Enter OTP",
        otpSent: "6-digit OTP sent to your number",
        demoNote: "📌 DEMO MODE: OTP shown on screen banner",
        verifyOTP: "Verify OTP ✓",
        resendOTP: "Resend OTP",
        goBack: "← Go Back",
        forgotPassword: "Forgot Password?",
        // Shop Setup
        aboutShop: "About Your Shop",
        shopSetupSubtitle: "This is needed only once. After this, manage your showroom!",
        shopNameLabel: "🏷️ What is your Shop Name?",
        shopNamePlaceholder: "Enter shop Name",
        ownerNameLabel: "👤 What is your Name (Owner)?",
        ownerNamePlaceholder: "e.g., Samyak Jain, Ravi Kumar...",
        startBtn: "🚀 Start Showroom!",
        // Sidebar
        dashboard: "Dashboard",
        inventory: "Inventory",
        customerBills: "Customer Bills",
        restockAlerts: "Restock Alerts",
        suppliers: "Suppliers & Payables",
        settings: "Settings",
        // Header
        createBill: "Create Bill",
        dashboardTitle: "Dashboard Overview",
        // Settings
        settingsTitle: "Store Configuration & Settings",
        shopProfileTitle: "🏪 Shop Profile",
        shopProfileDesc: "Edit your shop name, owner name, bill address and other details that appear on customer invoices.",
        shopNameField: "Shop Name",
        ownerNameField: "Owner Name",
        shopAddressField: "Shop Address (for bill)",
        shopAddressPlaceholder: "Enter address for bill",
        shopPhoneField: "Shop Phone (for bill)",
        shopPhoneFieldPlaceholder: "Enter shop phone",
        saveProfile: "💾 Save Profile",
        profileSaved: "✅ Shop profile saved!",
        // Lang
        languageTitle: "🌐 Language / भाषा",
        languageDesc: "Choose your preferred language. The app will update immediately.",
        // Forgot password
        forgotTitle: "Reset Password",
        forgotSubtitle: "Enter your registered phone/email to get OTP",
        resetContact: "Phone Number or Email",
        sendResetOTP: "Send Reset OTP",
        newPassword: "New Password",
        confirmNewPassword: "Confirm New Password",
        resetBtn: "Reset Password",
        passwordReset: "✅ Password reset successfully!",
        closeAndNewBtn: "New Bill",
        backToLogin: "← Back to Login",
        closeBtn: "Close",
        phoneNumber: "Phone Number",
        enterPhoneNumber: "Enter phone number",
        todayEarnings: "Today's Earnings",
        netProfitToday: "Net Profit today:",
        clothesSoldToday: "Clothes Sold Today",
        allApparelCats: "Across all apparel categories",
        totalStocked: "Total Clothes Stocked",
        worth: "Worth",
        inAssetCost: "in asset cost",
        lowStockAlert: "Low Stock Alert",
        needRestock: "Items need restocking immediately",
        recentTransactions: "Recent Transactions",
        noSalesLogged: "No sales logged yet. Click \"Create Bill\" to start!",
        quickOperations: "Quick Operations",
        createBillDesc: "Instantly make customer invoice and update stock",
        addClothes: "Add Clothes",
        addClothesDesc: "Add new patterns or garments to list",
        checkAlerts: "Check Alerts",
        checkAlertsDesc: "View items running below stock limit",
        resetDatabase: "Reset Database",
        resetDatabaseDesc: "Wipe all logs & reload demo dataset",
        salesProfitTrends: "Sales & Profit Trends (Last 7 Days)",
        stockDistribution: "Stock Distribution",
        // Tab titles
        tabInventoryTitle: "Clothes Stock Management",
        tabInventorySubtitle: "List, sort, search and modify garments cataloged in your store.",
        tabSalesTitle: "Customer Invoices",
        tabSalesSubtitle: "Full historical list of client bills and transaction receipts.",
        tabAlertsTitle: "Reorder Alerts",
        tabAlertsSubtitle: "A list of clothes that are low in stock and need replenishment.",
        tabSuppliersTitle: "Suppliers Ledger",
        tabSuppliersSubtitle: "Track distributor lists, payables, and outstanding settlement due dates.",
        tabSettingsSubtitle: "Add custom brands/categories, download CSV reports, and manage database.",
    },

    hi: {
        name: "हिंदी", flag: "🇮🇳",
        welcomeBack: "स्वागत है",
        dashboardSubtitle: "वापस स्वागत है, {owner}! आज {shop} का प्रदर्शन इस प्रकार है।",
        loginSubtitle: "अपने शोरूम में लॉगिन करें",
        emailPassword: "📧 ईमेल / पासवर्ड",
        phoneOTP: "📱 फोन नंबर",
        emailId: "ईमेल ID",
        password: "पासवर्ड",
        loginBtn: "लॉगिन करें",
        sendOTP: "OTP भेजें 📱",
        noAccount: "नया अकाउंट चाहिए?",
        signUpLink: "साइन अप करें",
        createAccount: "नया अकाउंट बनाएं",
        signupSubtitle: "अपना शोरूम रजिस्टर करें",
        yourName: "आपका नाम",
        howRegister: "कैसे रजिस्टर करें?",
        emailPwd: "ईमेल + पासवर्ड",
        phoneotp: "फोन OTP",
        confirmPassword: "पासवर्ड दोबारा डालें",
        createAccountBtn: "अकाउंट बनाएं ✨",
        alreadyAccount: "पहले से अकाउंट है?",
        loginLink: "लॉगिन करें",
        otpEnter: "OTP डालें",
        otpSent: "6-अंकों का OTP आपके नंबर पर भेजा गया",
        demoNote: "📌 डेमो मोड: OTP स्क्रीन पर दिखेगा",
        verifyOTP: "OTP वेरीफाई करें ✓",
        resendOTP: "OTP दोबारा भेजें",
        goBack: "← वापस जाएं",
        forgotPassword: "पासवर्ड भूल गए?",
        aboutShop: "आपकी दुकान के बारे में",
        shopSetupSubtitle: "यह जानकारी सिर्फ एक बार चाहिए। इसके बाद शोरूम मैनेज करें!",
        shopNameLabel: "🏷️ आपकी दुकान का नाम?",
        shopNamePlaceholder: "जैसे: सन्यम गारमेंट्स, राजू क्लॉथ हाउस...",
        ownerNameLabel: "👤 मालिक का नाम?",
        ownerNamePlaceholder: "जैसे: सम्यक जैन, राजू कुमार...",
        startBtn: "🚀 शोरूम शुरू करें!",
        dashboard: "डैशबोर्ड",
        inventory: "इन्वेंटरी",
        customerBills: "ग्राहक बिल",
        restockAlerts: "स्टॉक अलर्ट",
        suppliers: "सप्लायर्स",
        settings: "सेटिंग्स",
        createBill: "बिल बनाएं",
        dashboardTitle: "डैशबोर्ड ओवरव्यू",
        settingsTitle: "स्टोर सेटिंग्स",
        shopProfileTitle: "🏪 दुकान की जानकारी",
        shopProfileDesc: "दुकान का नाम, मालिक का नाम, पता और बिल की जानकारी बदलें।",
        shopNameField: "दुकान का नाम",
        ownerNameField: "मालिक का नाम",
        shopAddressField: "पता (बिल के लिए)",
        shopAddressPlaceholder: "जैसे: सरकारी अस्पताल के पास, बड़ागाँव, टीकमगढ़ - 472010",
        shopPhoneField: "फोन नंबर (बिल के लिए)",
        shopPhoneFieldPlaceholder: "जैसे: +91 9876543210",
        saveProfile: "💾 जानकारी सेव करें",
        profileSaved: "✅ दुकान की जानकारी सेव हो गई!",
        languageTitle: "🌐 भाषा / Language",
        languageDesc: "अपनी पसंदीदा भाषा चुनें। ऐप तुरंत अपडेट होगा।",
        forgotTitle: "पासवर्ड रीसेट करें",
        forgotSubtitle: "OTP पाने के लिए रजिस्टर्ड फोन/ईमेल डालें",
        resetContact: "फोन नंबर या ईमेल",
        sendResetOTP: "रीसेट OTP भेजें",
        newPassword: "नया पासवर्ड",
        confirmNewPassword: "पासवर्ड दोबारा डालें",
        resetBtn: "पासवर्ड रीसेट करें",
        passwordReset: "✅ पासवर्ड सफलतापूर्वक रीसेट हो गया!",
        closeAndNewBtn: "नया बिल",
        backToLogin: "← लॉगिन पर वापस",
        closeBtn: "बंद करें",
        phoneNumber: "फ़ोन नंबर",
        enterPhoneNumber: "फ़ोन नंबर डालें",
        todayEarnings: "आज की कमाई",
        netProfitToday: "आज का शुद्ध लाभ:",
        clothesSoldToday: "आज बिके कपड़े",
        allApparelCats: "सभी वस्त्र श्रेणियों में",
        totalStocked: "कुल कपड़े स्टॉक में",
        worth: "मूल्य",
        inAssetCost: "लागत मूल्य पर",
        lowStockAlert: "कम स्टॉक अलर्ट",
        needRestock: "सामान तुरंत रीस्टॉक करें",
        recentTransactions: "हाल के लेनदेन",
        noSalesLogged: "कोई बिक्री लॉग नहीं है। शुरू करने के लिए \"बिल बनाएं\" पर क्लिक करें!",
        quickOperations: "त्वरित संचालन",
        createBillDesc: "तुरंत ग्राहक का बिल बनाएं और स्टॉक अपडेट करें",
        addClothes: "कपड़े जोड़ें",
        addClothesDesc: "सूची में नए पैटर्न या वस्त्र जोड़ें",
        checkAlerts: "अलर्ट जांचें",
        checkAlertsDesc: "स्टॉक सीमा से नीचे चल रही वस्तुओं को देखें",
        resetDatabase: "डेटाबेस रीसेट करें",
        resetDatabaseDesc: "सभी लॉग मिटाएं और डेमो डेटा लोड करें",
        salesProfitTrends: "बिक्री और लाभ रुझान (पिछले 7 दिन)",
        stockDistribution: "स्टॉक वितरण",
        // Tab titles
        tabInventoryTitle: "कपड़े स्टॉक प्रबंधन",
        tabInventorySubtitle: "अपने शोरूम में दर्ज सभी कपड़े देखें, खोजें और बदलें।",
        tabSalesTitle: "ग्राहक बिल",
        tabSalesSubtitle: "सभी पुराने बिल और लेनदेन की पूरी सूची।",
        tabAlertsTitle: "रीऑर्डर अलर्ट",
        tabAlertsSubtitle: "वे कपड़े जो स्टॉक सीमा से नीचे हैं और भरने की जरूरत है।",
        tabSuppliersTitle: "सप्लायर खाता",
        tabSuppliersSubtitle: "वितरक सूची, देय राशि और बकाया भुगतान तिथियां ट्रैक करें।",
        tabSettingsSubtitle: "कस्टम श्रेणियां जोड़ें, CSV रिपोर्ट डाउनलोड करें और डेटाबेस प्रबंधित करें।",
    },

    gu: {
        name: "ગુજરાતી", flag: "🇮🇳",
        welcomeBack: "સ્વાગત છે",
        dashboardSubtitle: "સ્વાગત છે, {owner}! આજે {shop} નું પ્રદર્શન આ મુજબ છે.",
        loginSubtitle: "તમારા શોરૂમમાં લૉગિન કરો",
        emailPassword: "📧 ઈમેઈલ / પાસવર્ડ",
        phoneOTP: "📱 ફોન નંબર",
        emailId: "ઈમેઈલ ID",
        password: "પાસવર્ડ",
        loginBtn: "લૉગિન કરો",
        sendOTP: "OTP મોકલો 📱",
        noAccount: "નવું એકાઉન્ટ જોઈએ?",
        signUpLink: "સાઈન અપ કરો",
        createAccount: "નવું એકાઉન્ટ બનાવો",
        signupSubtitle: "તમારો શોરૂм નોંધો",
        yourName: "તમારું નામ",
        howRegister: "કેવી રીતે નોંધો?",
        emailPwd: "ઈમેઈલ + પાસવર્ડ",
        phoneotp: "ફોન OTP",
        confirmPassword: "પાસવર્ડ ફરીથી",
        createAccountBtn: "એકાઉન્ટ બનાવો ✨",
        alreadyAccount: "એકાઉન્ટ છે?",
        loginLink: "લૉગિન કરો",
        otpEnter: "OTP દાખલ કરો",
        otpSent: "6-અંકનો OTP મોકલ્યો",
        demoNote: "📌 ડેમો: OTP સ્ક્રીન પર દેખાશે",
        verifyOTP: "OTP ચકાસો ✓",
        resendOTP: "OTP ફરીથી મોકલો",
        goBack: "← પાછા જાઓ",
        forgotPassword: "પાસવર્ડ ભૂલ્યા?",
        aboutShop: "તમારી દુકાન વિશે",
        shopSetupSubtitle: "આ જાણકારી ફક્ત એક વખત જોઈએ!",
        shopNameLabel: "🏷️ દુકાનનું નામ?",
        shopNamePlaceholder: "જેમ: સન્યમ ગારમેન્ટ્સ...",
        ownerNameLabel: "👤 માલિકનું નામ?",
        ownerNamePlaceholder: "જેમ: સ્મ્યયak જૈન...",
        startBtn: "🚀 શોરૂм શરૂ કરો!",
        dashboard: "ડૅશબૉર્ડ",
        inventory: "ઇન્વેન્ટ્રી",
        customerBills: "ગ્રાહક બિલ",
        restockAlerts: "સ્ટૉક ઍલર્ટ",
        suppliers: "સપ્લાયર્સ",
        settings: "સેટિંગ્સ",
        createBill: "બિલ બનાવો",
        dashboardTitle: "ડૅશબૉર્ડ",
        settingsTitle: "સ્ટોર સેટિંગ્સ",
        shopProfileTitle: "🏪 દુકાનની માહિતી",
        shopProfileDesc: "દુકાનનું નામ, માલિકનું નામ, સરનામું બદલો.",
        shopNameField: "દુકાનનું નામ",
        ownerNameField: "માલિકનું નામ",
        shopAddressField: "સરનામું (બિલ માટે)",
        shopAddressPlaceholder: "જેમ: સ. હૉ. પાસે, ટીકામગઢ - 472010",
        shopPhoneField: "ફોન (બિલ માટે)",
        shopPhoneFieldPlaceholder: "જેમ: +91 9876543210",
        saveProfile: "💾 સેવ કરો",
        profileSaved: "✅ માહિતી સેવ થઈ!",
        languageTitle: "🌐 ભાષા / Language",
        languageDesc: "તમારી ભાષા પસંદ કરો.",
        forgotTitle: "પાસવર્ડ રીસેટ",
        forgotSubtitle: "OTP માટે ફોન/ઈમેઈલ નાખો",
        resetContact: "ફોન/ઈમેઈલ",
        sendResetOTP: "OTP મોકલો",
        newPassword: "નવો પાસવર્ડ",
        confirmNewPassword: "પાસવર્ડ ફરીથી",
        resetBtn: "રીસેટ કરો",
        passwordReset: "✅ પાસવર્ડ બદલ્યો!",
        closeAndNewBtn: "નવું બિલ",
        backToLogin: "← લૉગિન પર પાછા",
        closeBtn: "બંધ",
        phoneNumber: "ફોન નંબર",
        enterPhoneNumber: "ફોન નંબર દાખલ કરો",
        todayEarnings: "આજની કમાણી",
        netProfitToday: "આજનો ચોખ્ખો નફો:",
        clothesSoldToday: "આજે વેચેલા કપડાં",
        allApparelCats: "બધી કેટેગરીમાં",
        totalStocked: "ਕੁਲ ਸਟਾਕ ਕੀਤੇ ਕੱਪੜੇ",
        worth: "કિંમત",
        inAssetCost: "લાગત કિંમતમાં",
        lowStockAlert: "ઓછા સ્ટોકની ચેતવણી",
        needRestock: "તરત જ રીસ્ટોક કરો",
        recentTransactions: "તાજેતરના વ્યવહારો",
        noSalesLogged: "હજી સુધી કોઈ વેચાણ નોંધાયું નથી. શરૂ કરવા માટે \"બિલ બનાવો\" પર ક્લિક કરો!",
        quickOperations: "ઝડપી કામગીરી",
        createBillDesc: "તરત જ બિલ બનાવો અને સ્ટોક અપડેટ કરો",
        addClothes: "કપડાં ઉમેરો",
        addClothesDesc: "નવા પેટર્ન અથવા કપડાં ઉમેરો",
        checkAlerts: "ચેતવણીઓ તપાસો",
        checkAlertsDesc: "ઓછા સ્ટોક વાળી વસ્તુઓ જુઓ",
        resetDatabase: "ਡેટਾબેઝ રીસેટ કરો",
        resetDatabaseDesc: "બધા લોગ સાફ કરો અને ડેમો ડેટા લોડ કરો",
        salesProfitTrends: "વેચાણ અને નફાના વલણો (છેલ્લા 7 દિવસ)",
        stockDistribution: "સ્ટોક વિતરણ",
    },

    mr: {
        name: "मराठी", flag: "🇮🇳",
        welcomeBack: "स्वागत आहे",
        dashboardSubtitle: "स्वागत आहे, {owner}! आज {shop} ची कामगिरी अशी आहे.",
        loginSubtitle: "आपल्या शोरूममध्ये लॉगिन करा",
        emailPassword: "📧 ईमेल / पासवर्ड",
        phoneOTP: "📱 फोन नंबर",
        emailId: "ईमेल ID",
        password: "पासवर्ड",
        loginBtn: "लॉगिन करा",
        sendOTP: "OTP पाठवा 📱",
        noAccount: "नवीन खाते हवे आहे?",
        signUpLink: "साइन अप करा",
        createAccount: "नवीन खाते बनवा",
        signupSubtitle: "आपला शोरूम नोंदवा",
        yourName: "आपले नाव",
        howRegister: "कसे नोंदवायचे?",
        emailPwd: "ईमेल + पासवर्ड",
        phoneotp: "फोन OTP",
        confirmPassword: "पासवर्ड पुन्हा द्या",
        createAccountBtn: "खाते बनवा ✨",
        alreadyAccount: "आधीपासून खाते आहे?",
        loginLink: "लॉगिन करा",
        otpEnter: "OTP टाका",
        otpSent: "OTP आपल्या नंबरवर पाठवला",
        demoNote: "📌 डेमो: OTP स्क्रीनवर दिसेल",
        verifyOTP: "OTP तपासा ✓",
        resendOTP: "OTP पुन्हा पाठवा",
        goBack: "← मागे जा",
        forgotPassword: "पासवर्ड विसरलात?",
        aboutShop: "आपल्या दुकानाबद्दल",
        shopSetupSubtitle: "ही माहिती फक्त एकदाच लागेल!",
        shopNameLabel: "🏷️ दुकानाचे नाव?",
        shopNamePlaceholder: "जसे: सन्यम गारमेंट्स...",
        ownerNameLabel: "👤 मालकाचे नाव?",
        ownerNamePlaceholder: "जसे: सम्यक जैन...",
        startBtn: "🚀 शोरूम सुरू करा!",
        dashboard: "डॅशबोर्ड",
        inventory: "इन्व्हेंटरी",
        customerBills: "ग्राहक बिले",
        restockAlerts: "स्टॉक अलर्ट",
        suppliers: "पुरवठादार",
        settings: "सेटिंग्ज",
        createBill: "बिल बनवा",
        dashboardTitle: "डॅशबोर्ड",
        settingsTitle: "स्टोर सेटिंग्ज",
        shopProfileTitle: "🏪 दुकान माहिती",
        shopProfileDesc: "दुकानाचे नाव, मालकाचे नाव आणि पत्ता बदला.",
        shopNameField: "दुकानाचे नाव",
        ownerNameField: "मालकाचे नाव",
        shopAddressField: "पत्ता (बिलासाठी)",
        shopAddressPlaceholder: "जसे: सरकारी रुग्णालयाजवळ, टीकमगड - 472010",
        shopPhoneField: "फोन (बिलासाठी)",
        shopPhoneFieldPlaceholder: "जसे: +91 9876543210",
        saveProfile: "💾 जतन करा",
        profileSaved: "✅ माहिती जतन झाली!",
        languageTitle: "🌐 भाषा / Language",
        languageDesc: "आपली पसंतीची भाषा निवडा.",
        forgotTitle: "पासवर्ड रीसेट",
        forgotSubtitle: "OTP साठी फोन/ईमेल द्या",
        resetContact: "फोन/ईमेल",
        sendResetOTP: "रीसेट OTP पाठवा",
        newPassword: "नवीन पासवर्ड",
        confirmNewPassword: "पासवर्ड पुन्हा",
        resetBtn: "रीसेट करा",
        passwordReset: "✅ पासवर्ड बदलला!",
        closeAndNewBtn: "नवीन बिल",
        backToLogin: "← लॉगिनवर परत",
        closeBtn: "बंद करा",
        phoneNumber: "फोन नंबर",
        enterPhoneNumber: "फोन नंबर प्रविष्ट करा",
        todayEarnings: "आजची कमाई",
        netProfitToday: "आजचा निव्वळ नफा:",
        clothesSoldToday: "आज विकलेले कपडे",
        allApparelCats: "सर्व श्रेणींमध्ये",
        totalStocked: "एकूण उपलब्ध स्टॉक",
        worth: "किंमत",
        inAssetCost: "खरेदी किंमतीनुसार",
        lowStockAlert: "कमी स्टॉक अलर्ट",
        needRestock: "लवकरच रीस्टॉक करा",
        recentTransactions: "अलीकडील व्यवहार",
        noSalesLogged: "अद्याप कोणतीही विक्री नोंदवलेली नाही. सुरू करण्यासाठी \"बिल बनवा\" वर क्लिक करा!",
        quickOperations: "त्वरित कृती",
        createBillDesc: "त्वरित बिल बनवा आणि स्टॉक अपडेट करा",
        addClothes: "कपडे जोडा",
        addClothesDesc: "नवीन डिझाइन किंवा कपडे जोडा",
        checkAlerts: "अलर्ट तपासा",
        checkAlertsDesc: "कमी स्टॉक असलेल्या वस्तू पहा",
        resetDatabase: "डेटाबेस रीसेट करा",
        resetDatabaseDesc: "सर्व डेटा हटवा आणि डेमो डेटा लोड करा",
        salesProfitTrends: "बिक्री आणि नफा कल (गेले ७ दिवस)",
        stockDistribution: "स्टॉक वितरण",
    },

    pa: {
        name: "ਪੰਜਾਬੀ", flag: "🇮🇳",
        welcomeBack: "ਜੀ ਆਇਆ ਨੂੰ",
        dashboardSubtitle: "ਜੀ ਆਇਆ ਨੂੰ, {owner}! ਅੱਜ {shop} ਦਾ ਪ੍ਰਦਰਸ਼ਨ ਇਸ ਤਰ੍ਹਾਂ ਹੈ।",
        loginSubtitle: "ਆਪਣੇ ਸ਼ੋਰੂਮ ਵਿੱਚ ਲੌਗਿਨ ਕਰੋ",
        emailPassword: "📧 ਈਮੇਲ / ਪਾਸਵਰਡ",
        phoneOTP: "📱 ਫ਼ੋਨ ਨੰਬਰ",
        emailId: "ਈਮੇਲ ID",
        password: "ਪਾਸਵਰਡ",
        loginBtn: "ਲੌਗਿਨ ਕਰੋ",
        sendOTP: "OTP ਭੇਜੋ 📱",
        noAccount: "ਨਵਾਂ ਖਾਤਾ ਚਾਹੀਦਾ?",
        signUpLink: "ਸਾਈਨ ਅੱਪ ਕਰੋ",
        createAccount: "ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ",
        signupSubtitle: "ਆਪਣਾ ਸ਼ੋਰੂਮ ਰਜਿਸਟਰ ਕਰੋ",
        yourName: "ਤੁਹਾਡਾ ਨਾਮ",
        howRegister: "ਕਿਵੇਂ ਰਜਿਸਟਰ ਕਰਨਾ?",
        emailPwd: "ਈਮੇਲ + ਪਾਸਵਰਡ",
        phoneotp: "ਫ਼ੋਨ OTP",
        confirmPassword: "ਪਾਸਵਰਡ ਦੁਬਾਰਾ",
        createAccountBtn: "ਖਾਤਾ ਬਣਾਓ ✨",
        alreadyAccount: "ਖਾਤਾ ਹੈ?",
        loginLink: "ਲੌਗਿਨ ਕਰੋ",
        otpEnter: "OTP ਦਰਜ ਕਰੋ",
        otpSent: "OTP ਭੇਜਿਆ ਗਿਆ",
        demoNote: "📌 ਡੈਮੋ: OTP ਸਕਰੀਨ ਤੇ ਦਿਖੇਗਾ",
        verifyOTP: "OTP ਵੈਰੀਫਾਈ ✓",
        resendOTP: "OTP ਦੁਬਾਰਾ ਭੇਜੋ",
        goBack: "← ਵਾਪਸ",
        forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
        aboutShop: "ਤੁਹਾਡੀ ਦੁਕਾਨ ਬਾਰੇ",
        shopSetupSubtitle: "ਇਹ ਜਾਣਕਾਰੀ ਸਿਰਫ਼ ਇੱਕ ਵਾਰ ਚਾਹੀਦੀ!",
        shopNameLabel: "🏷️ ਦੁਕਾਨ ਦਾ ਨਾਮ?",
        shopNamePlaceholder: "ਜਿਵੇਂ: ਸੰਯਮ ਗਾਰਮੈਂਟਸ...",
        ownerNameLabel: "👤 ਮਾਲਕ ਦਾ ਨਾਮ?",
        ownerNamePlaceholder: "ਜਿਵੇਂ: ਸਮਯਕ ਜੈਨ...",
        startBtn: "🚀 ਸ਼ੋਰੂਮ ਸ਼ੁਰੂ ਕਰੋ!",
        dashboard: "ਡੈਸ਼ਬੋਰਡ", inventory: "ਇਨਵੈਂਟਰੀ",
        customerBills: "ਗਾਹਕ ਬਿੱਲ", restockAlerts: "ਸਟਾਕ ਅਲਰਟ",
        suppliers: "ਸਪਲਾਇਰ", settings: "ਸੈਟਿੰਗਾਂ",
        createBill: "ਬਿੱਲ ਬਣਾਓ", dashboardTitle: "ਡੈਸ਼ਬੋਰਡ",
        settingsTitle: "ਸਟੋਰ ਸੈਟਿੰਗਾਂ",
        shopProfileTitle: "🏪 ਦੁਕਾਨ ਜਾਣਕਾਰੀ",
        shopProfileDesc: "ਦੁਕਾਨ ਦਾ ਨਾਮ, ਮਾਲਕ ਦਾ ਨਾਮ ਅਤੇ ਪਤਾ ਬਦਲੋ।",
        shopNameField: "ਦੁਕਾਨ ਦਾ ਨਾਮ", ownerNameField: "ਮਾਲਕ ਦਾ ਨਾਮ",
        shopAddressField: "ਪਤਾ (ਬਿੱਲ ਲਈ)", shopAddressPlaceholder: "ਜਿਵੇਂ: ਟੀਕਮਗੜ੍ਹ - 472010",
        shopPhoneField: "ਫ਼ੋਨ (ਬਿੱਲ ਲਈ)", shopPhoneFieldPlaceholder: "ਜਿਵੇਂ: +91 9876543210",
        saveProfile: "💾 ਸੇਵ ਕਰੋ", profileSaved: "✅ ਜਾਣਕਾਰੀ ਸੇਵ!",
        languageTitle: "🌐 ਭਾਸ਼ਾ / Language", languageDesc: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ।",
        forgotTitle: "ਪਾਸਵਰਡ ਰੀਸੈੱਟ", forgotSubtitle: "ਫ਼ੋਨ/ਈਮੇਲ ਦਰਜ ਕਰੋ",
        resetContact: "ਫ਼ੋਨ/ਈਮੇਲ", sendResetOTP: "ਰੀਸੈੱਟ OTP ਭੇਜੋ",
        newPassword: "ਨਵਾਂ ਪਾਸਵਰਡ", confirmNewPassword: "ਪਾਸਵਰਡ ਦੁਬਾਰਾ",
        resetBtn: "ਰੀਸੈੱਟ", passwordReset: "✅ ਪਾਸਵਰਡ ਬਦਲਿਆ!",
        closeAndNewBtn: "ਨਵਾਂ ਬਿੱਲ",
        backToLogin: "← ਲੌਗਿਨ ਤੇ ਵਾਪਸ",
        closeBtn: "ਬੰਦ ਕਰੋ",
        phoneNumber: "ਫ਼ੋਨ ਨੰਬਰ",
        enterPhoneNumber: "ਫ਼ੋਨ ਨੰਬਰ ਦਰਜ ਕਰੋ",
        todayEarnings: "ਅੱਜ ਦੀ ਕਮਾਈ",
        netProfitToday: "ਅੱਜ ਦਾ ਸ਼ੁੱਧ ਮੁਨਾਫਾ:",
        clothesSoldToday: "ਅੱਜ ਵਿਕ ਗਏ ਕੱਪੜੇ",
        allApparelCats: "ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ ਵਿੱਚ",
        totalStocked: "ਕੁੱਲ ਸਟਾਕ ਕੀਤੇ ਕੱਪੜੇ",
        worth: "ਕੀਮਤ",
        inAssetCost: "ਲਾਗਤ ਮੁੱਲ ਤੇ",
        lowStockAlert: "ਘੱਟ ਸਟਾਕ ਅਲਰต์",
        needRestock: "ਤੁਰੰਤ ਰੀਸਟਾਕ ਕਰੋ",
        recentTransactions: "ਹਾਲੀਆ ਲੈਣ-ਦੇਣ",
        noSalesLogged: "ਅਜੇ ਤੱਕ ਕੋਈ ਵਿਕਰੀ ਦਰਜ ਨਹੀਂ ਹੋਈ। ਸ਼ੁਰੂ ਕਰਨ ਲਈ \"ਬਿੱਲ ਬਣਾਓ\" ਤੇ ਕਲਿੱक ਕਰੋ!",
        quickOperations: "ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ",
        createBillDesc: "ਤੁਰੰਤ ਗਾਹਕ ਦਾ ਬਿੱਲ ਬਣਾਓ ਅਤੇ ਸਟਾਕ ਅਪਡੇਟ ਕਰੋ",
        addClothes: "ਕੱਪੜੇ ਜੋੜੋ",
        addClothesDesc: "ਸੂਚੀ ਵਿੱਚ ਨਵੇਂ ਕੱਪੜੇ ਜੋੜੋ",
        checkAlerts: "ਅਲਰਟ ਚੈੱਕ ਕਰੋ",
        checkAlertsDesc: "ਘੱਟ ਸਟਾਕ ਵਾਲੀਆਂ ਚੀਜ਼ਾਂ ਦੇਖੋ",
        resetDatabase: "ਡਾਟਾਬੇਸ ਰੀਸੈੱਟ ਕਰੋ",
        resetDatabaseDesc: "ਸਾਰੇ ਲੌਗ ਮਿਟਾਓ ਅਤੇ ਡੈਮੋ ਡਾਟਾ ਲੋਡ ਕਰੋ",
        salesProfitTrends: "ਬਿਕਰੀ ਅਤੇ ਮੁਨਾਫਾ ਰੁਝਾਨ (ਪਿਛਲੇ 7 ਦਿਨ)",
        stockDistribution: "ਸਟਾਕ ਵੰਡ",
    },

    bn: {
        name: "বাংলা", flag: "🇧🇩",
        welcomeBack: "স্বাগতম",
        dashboardSubtitle: "স্বাগতম, {owner}! আজ {shop}-এর পারফরম্যান্স এইরকম।",
        loginSubtitle: "আপনার শোরুমে লগিন করুন",
        emailPassword: "📧 ইমেইল / পাসওয়ার্ড", phoneOTP: "📱 ফোন নম্বর",
        emailId: "ইমেইল ID", password: "পাসওয়ার্ড", loginBtn: "লগিন করুন",
        sendOTP: "OTP পাঠান 📱", noAccount: "নতুন অ্যাকাউন্ট দরকার?",
        signUpLink: "সাইন আপ করুন", createAccount: "নতুন অ্যাকাউন্ট তৈরি করুন",
        signupSubtitle: "শোরুম নিবন্ধন করুন", yourName: "আপনার নাম",
        howRegister: "কিভাবে নিবন্ধন করবেন?", emailPwd: "ইমেইল + পাসওয়ার্ড",
        phoneotp: "ফোন OTP", confirmPassword: "পাসওয়ার্ড নিশ্চিত করুন",
        createAccountBtn: "অ্যাকাউন্ট তৈরি করুন ✨", alreadyAccount: "অ্যাকাউন্ট আছে?",
        loginLink: "লগিন করুন", otpEnter: "OTP লিখুন", otpSent: "OTP পাঠানো হয়েছে",
        demoNote: "📌 ডেমো: OTP স্ক্রিনে দেখাবে", verifyOTP: "OTP যাচাই করুন ✓",
        resendOTP: "OTP পুনরায় পাঠান", goBack: "← ফিরে যান",
        forgotPassword: "পাসওয়ার্ড ভুলেছেন?",
        aboutShop: "আপনার দোকান সম্পর্কে", shopSetupSubtitle: "শুধু একবার দরকার!",
        shopNameLabel: "🏷️ দোকানের নাম?", shopNamePlaceholder: "যেমন: সন্যম গার্মেন্টস...",
        ownerNameLabel: "👤 মালিকের নাম?", ownerNamePlaceholder: "যেমন: সম্যক জৈন...",
        startBtn: "🚀 শোরুম শুরু করুন!",
        dashboard: "ড্যাশবোর্ড", inventory: "ইনভেন্টরি", customerBills: "গ্রাহক বিল",
        restockAlerts: "স্টক সতর্কতা", suppliers: "সরবরাহকারী", settings: "সেটিংস",
        createBill: "বিল তৈরি করুন", dashboardTitle: "ড্যাশবোর্ড",
        settingsTitle: "স্টোর সেটিংস", shopProfileTitle: "🏪 দোকান প্রোফাইল",
        shopProfileDesc: "দোকানের নাম, মালিকের নাম এবং ঠিকানা পরিবর্তন করুন।",
        shopNameField: "দোকানের নাম", ownerNameField: "মালিকের নাম",
        shopAddressField: "ঠিকানা (বিলের জন্য)", shopAddressPlaceholder: "যেমন: টিকামগড় - 472010",
        shopPhoneField: "ফোন (বিলের জন্য)", shopPhoneFieldPlaceholder: "যেমন: +91 9876543210",
        saveProfile: "💾 সংরক্ষণ করুন", profileSaved: "✅ প্রোফাইল সংরক্ষিত!",
        languageTitle: "🌐 ভাষা / Language", languageDesc: "পছন্দের ভাষা বেছে নিন।",
        forgotTitle: "পাসওয়ার্ড রিসেট", forgotSubtitle: "OTP পেতে ফোন/ইমেইল দিন",
        resetContact: "ফোন/ইমেইল", sendResetOTP: "রিসেট OTP পাঠান",
        newPassword: "নতুন পাসওয়ার্ড", confirmNewPassword: "পাসওয়ার্ড নিশ্চিত করুন",
        resetBtn: "রিসেট", passwordReset: "✅ পাসওয়ার্ড পরিবর্তিত!",
        closeAndNewBtn: "নতুন বিল",
        backToLogin: "← লগইনে ফিরুন",
        closeBtn: "বন্ধ করুন",
        phoneNumber: "ফোন নম্বর",
        enterPhoneNumber: "ফোন নম্বর লিখুন",
        todayEarnings: "আজকের উপার্জন",
        netProfitToday: "আজকের নিট লাভ:",
        clothesSoldToday: "আজকে বিক্রীত কাপড়",
        allApparelCats: "সব পোশাক বিভাগে",
        totalStocked: "মোট মজুদ কাপড়",
        worth: "মূল্য",
        inAssetCost: "ক্রয় মূল্যে",
        lowStockAlert: "কম স্টক সতর্কবার্তা",
        needRestock: "দ্রুত রিস্টক করুন",
        recentTransactions: "সাম্প্রতিক লেনদেন",
        noSalesLogged: "এখনো কোনো বিক্রি নথিভুক্ত করা হয়নি। শুরু করতে \"নতুন বিল\"-এ ক্লিক করুন!",
        quickOperations: "দ্রুত পরিচালনা",
        createBillDesc: "তাত্ক্ষণিকভাবে গ্রাহকের চালান তৈরি করুন এবং স্টক আপডেট করুন",
        addClothes: "কাপড় যুক্ত করুন",
        addClothesDesc: "তালিকায় নতুন প্যাটার্ন বা পোশাক যুক্ত করুন",
        checkAlerts: "সতর্কতা পরীক্ষা করুন",
        checkAlertsDesc: "স্টক সীমার নিচে থাকা পণ্যগুলি দেখুন",
        resetDatabase: "ডেটাবেস রিসেট করুন",
        resetDatabaseDesc: "সমস্ত লগ মুছুন এবং ডেমো ডেটা পুনরায় লোড করুন",
        salesProfitTrends: "বিক্রয় ও লাভের প্রবণতা (গত ৭ দিন)",
        stockDistribution: "স্টক বিতরণ",
    },

    te: {
        name: "తెలుగు", flag: "🇮🇳",
        welcomeBack: "స్వాగతం",
        dashboardSubtitle: "తిరిగి స్వాగతం, {owner}! ఈ రోజు {shop} పనితీరు ఇలా ఉంది.",
        loginSubtitle: "మీ షోరూంలో లాగిన్ అవ్వండి",
        emailPassword: "📧 ఇమెయిల్ / పాస్‌వర్డ్", phoneOTP: "📱 ఫోన్ నంబర్",
        emailId: "ఇమెయిల్ ID", password: "పాస్‌వర్డ్", loginBtn: "లాగిన్ చేయండి",
        sendOTP: "OTP పంపండి 📱", noAccount: "కొత్త ఖాతా కావాలా?",
        signUpLink: "సైన్ అప్", createAccount: "కొత్త ఖాతా తయారు చేయండి",
        signupSubtitle: "షోరూం నమోదు చేయండి", yourName: "మీ పేరు",
        howRegister: "ఎలా నమోదు చేయాలి?", emailPwd: "ఇమెయిల్ + పాస్‌వర్డ్",
        phoneotp: "ఫోన్ OTP", confirmPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
        createAccountBtn: "ఖాతా తయారు చేయండి ✨", alreadyAccount: "ఖాతా ఉందా?",
        loginLink: "లాగిన్", otpEnter: "OTP నమోదు చేయండి", otpSent: "OTP పంపబడింది",
        demoNote: "📌 డెమో: OTP స్క్రీన్‌పై కనిపిస్తుంది", verifyOTP: "OTP ధృవీకరించండి ✓",
        resendOTP: "OTP మళ్ళీ పంపండి", goBack: "← వెనక్కి", forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
        aboutShop: "మీ దుకాణం గురించి", shopSetupSubtitle: "ఒక్కసారే కావాలి!",
        shopNameLabel: "🏷️ దుకాణం పేరు?", shopNamePlaceholder: "ఉదా: సన్యమ్ గార్మెంట్స్...",
        ownerNameLabel: "👤 యజమాని పేరు?", ownerNamePlaceholder: "ఉదా: సమ్యక్ జైన్...",
        startBtn: "🚀 షోరూం ప్రారంభించండి!",
        dashboard: "డ్యాష్‌బోర్డ్", inventory: "ఇన్వెంటరీ", customerBills: "కస్టమర్ బిల్లులు",
        restockAlerts: "స్టాక్ హెచ్చరికలు", suppliers: "సప్లైయర్లు", settings: "సెట్టింగ్స్",
        createBill: "బిల్ తయారు చేయండి", dashboardTitle: "డ్యాష్‌బోర్డ్",
        settingsTitle: "స్టోర్ సెట్టింగ్స్", shopProfileTitle: "🏪 దుకాణ వివరాలు",
        shopProfileDesc: "దుకాణం పేరు, యజమాని పేరు, చిరునామా మార్చండి.",
        shopNameField: "దుకాణం పేరు", ownerNameField: "యజమాని పేరు",
        shopAddressField: "చిరునామా (బిల్ కోసం)", shopAddressPlaceholder: "ఉదా: టిక్కమగఢ్ - 472010",
        shopPhoneField: "ఫోన్ (బిల్ కోసం)", shopPhoneFieldPlaceholder: "ఉదా: +91 9876543210",
        saveProfile: "💾 సేవ్ చేయండి", profileSaved: "✅ వివరాలు సేవ్ అయ్యాయి!",
        languageTitle: "🌐 భాష / Language", languageDesc: "మీ భాషను ఎంచుకోండి.",
        forgotTitle: "పాస్‌వర్డ్ రీసెట్", forgotSubtitle: "ఫోన్/ఇమెయిల్ నమోదు చేయండి",
        resetContact: "ఫోన్/ఇమెయిల్", sendResetOTP: "రీసెట్ OTP పంపండి",
        newPassword: "కొత్త పాస్‌వర్డ్", confirmNewPassword: "పాస్‌వర్డ్ నిర్ధారించండి",
        resetBtn: "రీసెట్ చేయండి", passwordReset: "✅ పాస్‌వర్డ్ మార్చబడింది!",
        closeAndNewBtn: "కొత్త బిల్లు",
        backToLogin: "← లాగిన్‌కు తిరిగి",
        closeBtn: "మూసివేయి",
        phoneNumber: "ఫోన్ నంబర్",
        enterPhoneNumber: "ఫోన్ నంబర్ నమోదు చేయండి",
        todayEarnings: "నేటి ఆదాయం",
        netProfitToday: "ఈ రోజు నికర లాభం:",
        clothesSoldToday: "ఈ రోజు అమ్మిన బట్టలు",
        allApparelCats: "అన్ని రకాల బట్టలలో",
        totalStocked: "మొత్తం అందుబాటులో ఉన్న స్టాక్",
        worth: "విలువ",
        inAssetCost: "కొనుగోలు ధర ప్రకారం",
        lowStockAlert: "తక్కువ స్టాక్ హెచ్చరిక",
        needRestock: "వెంటనే రీస్టాక్ చేయండి",
        recentTransactions: "ఇటీవలి లావాదేవీలు",
        noSalesLogged: "ఇంకా ఎలాంటి విక్రయాలు నమోదు కాలేదు. ప్రారంభించడానికి \"బిల్లు చేయండి\" క్లిక్ చేయండి!",
        quickOperations: "త్వరిత కార్యకలాపాలు",
        createBillDesc: "వెంటనే కస్టమర్ బిల్లు చేసి స్టాక్ అప్‌డేట్ చేయండి",
        addClothes: "బట్టలు జోడించండి",
        addClothesDesc: "లిస్టులో కొత్త బట్టల రకాలు జోడించండి",
        checkAlerts: "హెచ్చరికలు చూడండి",
        checkAlertsDesc: "తక్కువ స్టాక్ ఉన్న వస్తువులను చూడండి",
        resetDatabase: "డేటాబేస్ రీసెట్ చేయండి",
        resetDatabaseDesc: "అన్ని లాగ్స్ తొలగించి డెమో డేటా లోడ్ చేయండి",
        salesProfitTrends: "అమ్మకాలు & లాభాల సరళి (గత 7 రోజులు)",
        stockDistribution: "స్టాక్ పంపిణీ",
    },

    ta: {
        name: "தமிழ்", flag: "🇮🇳",
        welcomeBack: "வரவேற்கிறோம்",
        dashboardSubtitle: "நல்வரவு, {owner}! இன்று {shop}-இன் செயல்பாடு இவ்வாறு உள்ளது.",
        loginSubtitle: "உங்கள் ஷோரூமில் உள்நுழையுங்கள்",
        emailPassword: "📧 மின்னஞ்சல் / கடவுச்சொல்", phoneOTP: "📱 தொலைபேசி எண்",
        emailId: "மின்னஞ்சல் ID", password: "கடவுச்சொல்", loginBtn: "உள்நுழை",
        sendOTP: "OTP அனுப்பு 📱", noAccount: "புதிய கணக்கு வேண்டுமா?",
        signUpLink: "பதிவு செய்", createAccount: "புதிய கணக்கு உருவாக்கு",
        signupSubtitle: "உங்கள் ஷோரூமை பதிவு செய்யுங்கள்", yourName: "உங்கள் பெயர்",
        howRegister: "எப்படி பதிவு செய்வது?", emailPwd: "மின்னஞ்சல் + கடவுச்சொல்",
        phoneotp: "தொலைபேசி OTP", confirmPassword: "கடவுச்சொல் உறுதிப்படுத்து",
        createAccountBtn: "கணக்கு உருவாக்கு ✨", alreadyAccount: "கணக்கு உள்ளதா?",
        loginLink: "உள்நுழை", otpEnter: "OTP உள்ளிடவும்", otpSent: "OTP அனுப்பப்பட்டது",
        demoNote: "📌 டெமோ: OTP திரையில் காட்டப்படும்", verifyOTP: "OTP சரிபார்க்கவும் ✓",
        resendOTP: "OTP மீண்டும் அனுப்பு", goBack: "← திரும்பு", forgotPassword: "கடவுச்சொல் மறந்தீர்களா?",
        aboutShop: "உங்கள் கடை பற்றி", shopSetupSubtitle: "இந்த தகவல் ஒரு முறை மட்டுமே!",
        shopNameLabel: "🏷️ கடையின் பெயர்?", shopNamePlaceholder: "எ.கா: சன்யம் கார்மென்ட்ஸ்...",
        ownerNameLabel: "👤 உரிமையாளர் பெயர்?", ownerNamePlaceholder: "எ.கா: சம்யக் ஜைன்...",
        startBtn: "🚀 ஷோரூம் தொடங்கு!",
        dashboard: "டாஷ்போர்டு", inventory: "சரக்கு", customerBills: "வாடிக்கையாளர் பில்கள்",
        restockAlerts: "சரக்கு எச்சரிக்கைகள்", suppliers: "சப்ளையர்கள்", settings: "அமைப்புகள்",
        createBill: "பில் உருவாக்கு", dashboardTitle: "டாஷ்போர்டு",
        settingsTitle: "கடை அமைப்புகள்", shopProfileTitle: "🏪 கடை விவரங்கள்",
        shopProfileDesc: "கடையின் பெயர், முகவரி மாற்றவும்.",
        shopNameField: "கடையின் பெயர்", ownerNameField: "உரிமையாளர் பெயர்",
        shopAddressField: "முகவரி (பில் க்காக)", shopAddressPlaceholder: "எ.கா: டிகாம்கர் - 472010",
        shopPhoneField: "தொலைபேசி (பில் க்காக)", shopPhoneFieldPlaceholder: "எ.கா: +91 9876543210",
        saveProfile: "💾 சேமி", profileSaved: "✅ சேமிக்கப்பட்டது!",
        languageTitle: "🌐 மொழி / Language", languageDesc: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்.",
        forgotTitle: "கடவுச்சொல் மீட்டமை", forgotSubtitle: "தொலைபேசி/மின்னஞ்சல் உள்ளிடவும்",
        resetContact: "தொலைபேசி/மின்னஞ்சல்", sendResetOTP: "மீட்டமை OTP அனுப்பு",
        newPassword: "புதிய கடவுச்சொல்", confirmNewPassword: "கடவுச்சொல் உறுதிப்படுத்து",
        resetBtn: "மீட்டமை", passwordReset: "✅ கடவுச்சொல் மாற்றப்பட்டது!",
        closeAndNewBtn: "புதிய பில்",
        backToLogin: "← உள்நுழைவுக்கு திரும்பு",
        closeBtn: "மூடு",
        phoneNumber: "தொலைபேசி எண்",
        enterPhoneNumber: "தொலைபேசி எண்ணை உள்ளிடவும்",
        todayEarnings: "இன்றைய வருவாய்",
        netProfitToday: "இன்றைய நிகர லாபம்:",
        clothesSoldToday: "இன்று விற்பனையான ஆடைகள்",
        allApparelCats: "அனைத்து ஆடை வகைகளிலும்",
        totalStocked: "மொத்த ஆடை இருப்பு",
        worth: "மதிப்பு",
        inAssetCost: "அசல் கொள்முதல் விலையில்",
        lowStockAlert: "குறைந்த இருப்பு எச்சரிக்கை",
        needRestock: "உடனடியாக இருப்பை நிரப்பவும்",
        recentTransactions: "சமீபத்திய பரிவர்த்தனைகள்",
        noSalesLogged: "இதுவரை விற்பனை ஏதும் பதிவு செய்யப்படவில்லை. தொடங்க \"பில் உருவாக்கு\" கிளிக் செய்யவும்!",
        quickOperations: "விரைவான செயல்பாடுகள்",
        createBillDesc: "உடனடியாக வாடிக்கையாளர் பில் உருவாக்கி இருப்பை புதுப்பிக்கவும்",
        addClothes: "ஆடைகளை சேர்க்கவும்",
        addClothesDesc: "பட்டியலில் புதிய ஆடைகளை சேர்க்கவும்",
        checkAlerts: "எச்சரிக்கைகளைச் சரிபார்க்கவும்",
        checkAlertsDesc: "குறைந்த இருப்பிலுள்ள பொருட்களைப் பார்க்கவும்",
        resetDatabase: "தரவுத்தளத்தை மீட்டமைக்கவும்",
        resetDatabaseDesc: "அனைத்து பதிவுகளையும் அழித்து டெமோ தரவை ஏற்றவும்",
        salesProfitTrends: "விற்பனை மற்றும் லாப போக்குகள் (கடந்த 7 நாட்கள்)",
        stockDistribution: "இருப்பு விநியோகம்",
    },

    kn: {
        name: "ಕನ್ನಡ", flag: "🇮🇳",
        welcomeBack: "ಸ್ವಾಗತ",
        dashboardSubtitle: "ಮರಳಿ ಸ್ವಾಗತ, {owner}! ಇಂದು {shop} ಕಾರ್ಯಕ್ಷಮತೆ ಹೀಗಿದೆ.",
        loginSubtitle: "ನಿಮ್ಮ ಶೋರೂಮ್‌ಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
        emailPassword: "📧 ಇಮೇಲ್ / ಪಾಸ್‌ವರ್ಡ್", phoneOTP: "📱 ಫೋನ್ ಸಂಖ್ಯೆ",
        emailId: "ಇಮೇಲ್ ID", password: "ಪಾಸ್‌ವರ್ಡ್", loginBtn: "ಲಾಗಿನ್ ಮಾಡಿ",
        sendOTP: "OTP ಕಳುಹಿಸಿ 📱", noAccount: "ಹೊಸ ಖಾತೆ ಬೇಕೇ?",
        signUpLink: "ಸೈನ್ ಅಪ್ ಮಾಡಿ", createAccount: "ಹೊಸ ಖಾತೆ ಮಾಡಿ",
        signupSubtitle: "ಶೋರೂಮ್ ನೋಂದಾಯಿಸಿ", yourName: "ನಿಮ್ಮ ಹೆಸರು",
        howRegister: "ಹೇಗೆ ನೋಂದಾಯಿಸಬೇಕು?", emailPwd: "ಇಮೇಲ್ + ಪಾಸ್‌ವರ್ಡ್",
        phoneotp: "ಫೋನ್ OTP", confirmPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢಪಡಿಸಿ",
        createAccountBtn: "ಖಾತೆ ಮಾಡಿ ✨", alreadyAccount: "ಖಾತೆ ಇದೆಯೇ?",
        loginLink: "ಲಾಗಿನ್", otpEnter: "OTP ನಮೂದಿಸಿ", otpSent: "OTP ಕಳುಹಿಸಲಾಗಿದೆ",
        demoNote: "📌 ಡೆಮೋ: OTP ಸ್ಕ್ರೀನ್‌ನಲ್ಲಿ ತೋರಿಸುತ್ತದೆ", verifyOTP: "OTP ಪರಿಶೀಲಿಸಿ ✓",
        resendOTP: "OTP ಮರು-ಕಳುಹಿಸಿ", goBack: "← ಹಿಂದೆ", forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
        aboutShop: "ನಿಮ್ಮ ಅಂಗಡಿ ಬಗ್ಗೆ", shopSetupSubtitle: "ಇದು ಒಮ್ಮೆ ಮಾತ್ರ!",
        shopNameLabel: "🏷️ ಅಂಗಡಿ ಹೆಸರು?", shopNamePlaceholder: "ಉದಾ: ಸನ್ಯಮ್ ಗಾರ್ಮೆಂಟ್ಸ್...",
        ownerNameLabel: "👤 ಮಾಲೀಕರ ಹೆಸರು?", ownerNamePlaceholder: "ಉದಾ: ಸಮ್ಯಕ್ ಜೈನ್...",
        startBtn: "🚀 ಶೋರೂಮ್ ಶುರು ಮಾಡಿ!",
        dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", inventory: "ಇನ್ವೆಂಟರಿ", customerBills: "ಗ್ರಾಹಕ ಬಿಲ್‌ಗಳು",
        restockAlerts: "ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆಗಳು", suppliers: "ಪೂರೈಕೆದಾರರು", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
        createBill: "ಬಿಲ್ ಮಾಡಿ", dashboardTitle: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
        settingsTitle: "ಸ್ಟೋರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು", shopProfileTitle: "🏪 ಅಂಗಡಿ ವಿವರಗಳು",
        shopProfileDesc: "ಅಂಗಡಿ ಹೆಸರು, ವಿಳಾಸ ಬದಲಾಯಿಸಿ.",
        shopNameField: "ಅಂಗಡಿ ಹೆಸರು", ownerNameField: "ಮಾಲೀಕರ ಹೆಸರು",
        shopAddressField: "ವಿಳಾಸ (ಬಿಲ್‌ಗೆ)", shopAddressPlaceholder: "ಉದಾ: ಟಿಕಮ್‌ಗಡ - 472010",
        shopPhoneField: "ಫೋನ್ (ಬಿಲ್‌ಗೆ)", shopPhoneFieldPlaceholder: "ಉದಾ: +91 9876543210",
        saveProfile: "💾 ಉಳಿಸಿ", profileSaved: "✅ ಉಳಿಸಲಾಗಿದೆ!",
        languageTitle: "🌐 ಭಾಷೆ / Language", languageDesc: "ನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ.",
        forgotTitle: "ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್", forgotSubtitle: "ಫೋನ್/ಇಮೇಲ್ ನಮೂದಿಸಿ",
        resetContact: "ಫೋನ್/ಇಮೇಲ್", sendResetOTP: "ರೀಸೆಟ್ OTP ಕಳುಹಿಸಿ",
        newPassword: "ಹೊಸ ಪಾಸ್‌ವರ್ಡ್", confirmNewPassword: "ಪಾಸ್‌ವರ್ಡ್ ದೃಢಪಡಿಸಿ",
        resetBtn: "ರೀಸೆಟ್", passwordReset: "✅ ಪಾಸ್ವರ್ಡ್ ಬದಲಾಗಿದೆ!",
        closeAndNewBtn: "ಹೊಸ ಬಿಲ್",
        backToLogin: "← ಲಾಗಿನ್‌ಗೆ ಹಿಂದೆ",
        closeBtn: "ಮುಚ್ಚಿ",
        phoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆ",
        enterPhoneNumber: "ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ",
        todayEarnings: "ಇಂದಿನ ಗಳಿಕೆ",
        netProfitToday: "ಇಂದಿನ ನಿವ್ವಳ ಲಾಭ:",
        clothesSoldToday: "ಇಂದು ಮಾರಾಟವಾದ ಬಟ್ಟೆಗಳು",
        allApparelCats: "ಎಲ್ಲಾ ಬಟ್ಟೆ ವಿಭಾಗಗಳಲ್ಲಿ",
        totalStocked: "ಒಟ್ಟು ದಾಸ್ತಾನು ಬಟ್ಟೆಗಳು",
        worth: "ಮೌಲ್ಯ",
        inAssetCost: "ಖರೀದಿ ವೆಚ್ಚದಲ್ಲಿ",
        lowStockAlert: "ಕಡಿಮೆ ದಾಸ್ತಾನು ಎಚ್ಚರಿಕೆ",
        needRestock: "ಕೂಡಲೇ ದಾಸ್ತಾನು ಭರ್ತಿ ಮಾಡಿ",
        recentTransactions: "ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು",
        noSalesLogged: "ಇನ್ನೂ ಯಾವುದೇ ಮಾರಾಟ ದಾಖಲಾಗಿಲ್ಲ. ಪ್ರಾರಂಭಿಸಲು \"ಬಿಲ್ ಮಾಡಿ\" ಕ್ಲಿಕ್ ಮಾಡಿ!",
        quickOperations: "ತ್ವರಿತ ಕಾರ್ಯಾಚರಣೆಗಳು",
        createBillDesc: "ಕೂಡಲೇ ಗ್ರಾಹಕರ ಬಿಲ್ ಮಾಡಿ ದಾಸ್ತಾನು ನವೀಕರಿಸಿ",
        addClothes: "ಬಟ್ಟೆಗಳನ್ನು ಸೇರಿಸಿ",
        addClothesDesc: "ಪಟ್ಟಿಗೆ ಹೊಸ ಬಟ್ಟೆಗಳನ್ನು ಸೇರಿಸಿ",
        checkAlerts: "ಎಚ್ಚರಿಕೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ",
        checkAlertsDesc: "ಕಡಿಮೆ ದಾಸ್ತಾನು ಇರುವ ವಸ್ತುಗಳನ್ನು ನೋಡಿ",
        resetDatabase: "ಡೇಟಾಬೇಸ್ ಮರುಹೊಂದಿಸಿ",
        resetDatabaseDesc: "ಎಲ್ಲಾ ದಾಖಲೆಗಳನ್ನು ಅಳಿಸಿ ಡೆಮೊ ಡೇಟಾವನ್ನು ಲೋಡ್ ಮಾಡಿ",
        salesProfitTrends: "ಮಾರಾಟ ಮತ್ತು ಲಾಭದ ಪ್ರವೃತ್ತಿ (ಕಳೆದ 7 ದಿನಗಳು)",
        stockDistribution: "ದಾಸ್ತಾನು ಹಂಚಿಕೆ",
    },

    ml: {
        name: "മലയാളം", flag: "🇮🇳",
        welcomeBack: "സ്വാഗതം",
        dashboardSubtitle: "തിരികെ സ്വാഗതം, {owner}! ഇന്ന് {shop}-ന്റെ പ്രകടനം താഴെ പറയുന്നതാണ്.",
        loginSubtitle: "ഷോറൂമിൽ ലോഗിൻ ചെയ്യുക",
        emailPassword: "📧 ഇമെയിൽ / പാസ്‌വേഡ്", phoneOTP: "📱 ഫോൺ നമ്പർ",
        emailId: "ഇമെയിൽ ID", password: "പാസ്‌വേഡ്", loginBtn: "ലോഗിൻ ചെയ്യുക",
        sendOTP: "OTP അയക്കുക 📱", noAccount: "പുതിയ അക്കൗണ്ട് വേണോ?",
        signUpLink: "സൈൻ അപ്പ്", createAccount: "പുതിയ അക്കൗണ്ട്",
        signupSubtitle: "ഷോറൂം രജിസ്റ്റർ ചെയ്യുക", yourName: "നിങ്ങളുടെ പേര്",
        howRegister: "എങ്ങനെ രജിസ്റ്റർ?", emailPwd: "ഇമെയിൽ + പാസ്‌വേഡ്",
        phoneotp: "ഫോൺ OTP", confirmPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
        createAccountBtn: "അക്കൗണ്ട് ഉണ്ടാക്കുക ✨", alreadyAccount: "അക്കൗണ്ട് ഉണ്ടോ?",
        loginLink: "ലോഗിൻ", otpEnter: "OTP നൽകുക", otpSent: "OTP അയച്ചു",
        demoNote: "📌 ഡെമോ: OTP സ്ക്രീനിൽ കാണും", verifyOTP: "OTP സ്ഥിരീകരിക്കുക ✓",
        resendOTP: "OTP വീണ്ടും അയക്കുക", goBack: "← തിരിച്ചു", forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
        aboutShop: "നിങ്ങളുടെ കട", shopSetupSubtitle: "ഒരിക്കൽ മാത്രം!",
        shopNameLabel: "🏷️ കടയുടെ പേര്?", shopNamePlaceholder: "ഉദാ: സന്യം ഗാർമെന്റ്സ്...",
        ownerNameLabel: "👤 ഉടമയുടെ പേര്?", ownerNamePlaceholder: "ഉദാ: സമ്യക് ജൈൻ...",
        startBtn: "🚀 ഷോറൂം തുടങ്ങൂ!",
        dashboard: "ഡാഷ്‌ബോർഡ്", inventory: "ഇൻവെന്ററി", customerBills: "ഉപഭോക്തൃ ബില്ലുകൾ",
        restockAlerts: "സ്റ്റോക്ക് മുന്നറിയിപ്പ്", suppliers: "വിതരണക്കാർ", settings: "ക്രമീകരണം",
        createBill: "ബിൽ ഉണ്ടാക്കുക", dashboardTitle: "ഡാഷ്‌ബോർഡ്",
        settingsTitle: "സ്റ്റോർ ക്രമീകരണം", shopProfileTitle: "🏪 കട വിവരങ്ങൾ",
        shopProfileDesc: "കടയുടെ പേര്, വിലാസം മാറ്റുക.",
        shopNameField: "കടയുടെ പേര്", ownerNameField: "ഉടമയുടെ പേര്",
        shopAddressField: "വിലാസം (ബില്ലിന്)", shopAddressPlaceholder: "ഉദാ: ടിക്കംഗഡ് - 472010",
        shopPhoneField: "ഫോൺ (ബില്ലിന്)", shopPhoneFieldPlaceholder: "ഉദാ: +91 9876543210",
        saveProfile: "💾 സേവ് ചെയ്യുക", profileSaved: "✅ സേവ് ആയി!",
        languageTitle: "🌐 ഭാഷ / Language", languageDesc: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക.",
        forgotTitle: "പാസ്‌വേഡ് റീസെറ്റ്", forgotSubtitle: "ഫോൺ/ഇമെയിൽ നൽകുക",
        resetContact: "ഫോൺ/ഇമെയിൽ", sendResetOTP: "റീസെറ്റ് OTP അയക്കുക",
        newPassword: "പുതിയ പാസ്‌വേഡ്", confirmNewPassword: "പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക",
        resetBtn: "റീസെറ്റ് ചെയ്യുക", passwordReset: "✅ പാസ്‌വേഡ് മാറ്റി!",
        closeAndNewBtn: "പുതിയ ബിൽ",
        backToLogin: "← ലോഗിനിലേക്ക് മടങ്ങൂ",
        closeBtn: "അടക്കുക",
        phoneNumber: "ഫോൺ നമ്പർ",
        enterPhoneNumber: "ഫോൺ നമ്പർ നൽകുക",
        todayEarnings: "ഇന്നത്തെ വരുമാനം",
        netProfitToday: "ഇന്നത്തെ അറ്റാദായം:",
        clothesSoldToday: "ഇന്ന് വിറ്റ വസ്ത്രങ്ങൾ",
        allApparelCats: "എല്ലാ വസ്ത്ര വിഭാഗങ്ങളിലും",
        totalStocked: "ആകെ സ്റ്റോക്കുള്ള വസ്ത്രങ്ങൾ",
        worth: "മൂല്യം",
        inAssetCost: "അസറ്റ് വിലയിൽ",
        lowStockAlert: "കുറഞ്ഞ സ്റ്റോക്ക് മുന്നറിയിപ്പ്",
        needRestock: "ഉടൻ തന്നെ സ്റ്റോക്ക് പുതുക്കുക",
        recentTransactions: "സമീപകാല ഇടപാടുകൾ",
        noSalesLogged: "ഇതുവരെ വിൽപ്പനയൊന്നും രേഖപ്പെടുത്തിയിട്ടില്ല. ആരംഭിക്കാൻ \"പുതിയ ബിൽ\" ക്ലിക്ക് ചെയ്യുക!",
        quickOperations: "ദ്രുത പ്രവർത്തനങ്ങൾ",
        createBillDesc: "ഉടൻ തന്നെ കസ്റ്റമർ ബിൽ ഉണ്ടാക്കി സ്റ്റോക്ക് പുതുക്കുക",
        addClothes: "വസ്ത്രങ്ങൾ ചേർക്കുക",
        addClothesDesc: "ലിസ്റ്റിലേക്ക് പുതിയ വസ്ത്രങ്ങൾ ചേർക്കുക",
        checkAlerts: "അലർട്ടുകൾ പരിശോധിക്കുക",
        checkAlertsDesc: "കുറഞ്ഞ സ്റ്റോക്കുള്ള സാധനങ്ങൾ കാണുക",
        resetDatabase: "ഡാറ്റാബേസ് റീസെറ്റ് ചെയ്യുക",
        resetDatabaseDesc: "എല്ലാ വിവരങ്ങളും മായ്ച്ച് ഡെമോ ഡാറ്റ ലോഡ് ചെയ്യുക",
        salesProfitTrends: "വിൽപ്പന & ലാഭ പ്രവണതകൾ (കഴിഞ്ഞ 7 ദിവസം)",
        stockDistribution: "സ്റ്റോക്ക് വിതരണം",
    },
};

// ─── Language Manager ─────────────────────────────────────────
const LangManager = {
    current: 'en',

    init() {
        const saved = localStorage.getItem('sm_language') || 'en';
        this.current = LANGUAGES[saved] ? saved : 'en';
        this.apply();
        this.initAuthLangSelect();
    },

    set(code) {
        if (!LANGUAGES[code]) return;
        this.current = code;
        localStorage.setItem('sm_language', code);
        this.apply();
        this.initAuthLangSelect();
        if (window.initLanguageGrid) window.initLanguageGrid();
    },

    t(key) {
        const lang = LANGUAGES[this.current] || LANGUAGES['en'];
        return lang[key] || LANGUAGES['en'][key] || key;
    },

    initAuthLangSelect() {
        const select = document.getElementById('auth-lang-select');
        if (!select) return;
        select.innerHTML = '';
        Object.entries(LANGUAGES).forEach(([code, lang]) => {
            const opt = document.createElement('option');
            opt.value = code;
            opt.textContent = `${lang.flag} ${lang.name}`;
            if (code === this.current) opt.selected = true;
            select.appendChild(opt);
        });

        if (!select._changeHandlerAdded) {
            select._changeHandlerAdded = true;
            select.addEventListener('change', (e) => {
                this.set(e.target.value);
                if (window.app) window.app.showNotification(`🌐 Language changed to ${LANGUAGES[e.target.value].name}`);
            });
        }
    },

    // Sync ALL language dropdowns on the page
    syncAllSelects() {
        document.querySelectorAll('.lang-select-dropdown').forEach(select => {
            if (select.innerHTML.trim() === '') {
                Object.entries(LANGUAGES).forEach(([code, lang]) => {
                    const opt = document.createElement('option');
                    opt.value = code;
                    opt.textContent = `${lang.flag} ${lang.name}`;
                    select.appendChild(opt);
                });
                if (!select._changeHandlerAdded) {
                    select._changeHandlerAdded = true;
                    select.addEventListener('change', (e) => {
                        this.set(e.target.value);
                        if (window.app) window.app.showNotification(`🌐 Language changed to ${LANGUAGES[e.target.value].name}`);
                    });
                }
            }
            // Sync selected value
            select.value = this.current;
        });
        // Also sync auth-lang-select
        const authSel = document.getElementById('auth-lang-select');
        if (authSel) authSel.value = this.current;
        // Also sync settings lang select if it exists
        const settSel = document.getElementById('settings-lang-select');
        if (settSel) settSel.value = this.current;
    },

    apply() {
        // Update all elements with data-lang attribute
        // Use smart text replacement that preserves child elements (icons)
        document.querySelectorAll('[data-lang]').forEach(el => {
            const key = el.getAttribute('data-lang');
            const val = this.t(key);
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                el.placeholder = val;
            } else if (el.tagName === 'OPTION') {
                el.textContent = val;
            } else {
                // Check if element has child elements (like icons)
                const hasChildElements = el.children.length > 0;
                if (hasChildElements) {
                    // Find and update only text nodes, preserve child elements
                    let textNodeFound = false;
                    el.childNodes.forEach(node => {
                        if (node.nodeType === Node.TEXT_NODE && node.textContent.trim()) {
                            node.textContent = val;
                            textNodeFound = true;
                        }
                    });
                    // If no text node found, prepend text
                    if (!textNodeFound) {
                        // Check if there's a <span> that is the text carrier
                        const spanChild = el.querySelector('span:not([data-lang]):not([class])') || el.querySelector('span');
                        if (spanChild && !spanChild.getAttribute('data-lang')) {
                            spanChild.textContent = val;
                        } else {
                            // Safe fallback: set textContent (will wipe icons - only for simple elements)
                            el.textContent = val;
                        }
                    }
                } else {
                    el.textContent = val;
                }
            }
        });

        // Update data-lang-placeholder elements
        document.querySelectorAll('[data-lang-placeholder]').forEach(el => {
            el.placeholder = this.t(el.getAttribute('data-lang-placeholder'));
        });

        // Update lucide icons (re-render if needed)
        if (window.lucide) lucide.createIcons();

        // Sync all language dropdowns
        this.syncAllSelects();

        // Update dynamic welcome text if logged in
        if (window.AuthUI && window.AuthUI.updateAppWithUserInfo) {
            AuthUI.updateAppWithUserInfo();
        }

        // Update dashboard/app stats dynamically if active
        if (window.app && window.app.renderAll) {
            window.app.renderAll();
        }
    }
};

// Initialize on load
document.addEventListener('DOMContentLoaded', () => LangManager.init());

// Expose to global scope for other scripts
window.LANGUAGES = LANGUAGES;
window.LangManager = LangManager;
